import type { Metadata } from "next";
import { Jersey_10, Montserrat, Yaldevi } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const font = Montserrat({ subsets: ["latin"], variable: "--font-sans" });
const jersey = Jersey_10({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Clodron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "bg-neutral-950 text-white antialiased font-sans",
          jersey.variable,
          font.variable,
        )}>
        {children}
      </body>
    </html>
  );
}
